Develop ben aug29
AdobeDocs/pdfservices-api-documentation pull request #240
Opened 2022-08-30 06:38 UTC by piyuverma

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-08-30 11:39 UTC, adityaganotra commented on src/pages/overview/pdf-electronic-seal-api/index.md
> +# Overview
Please add title related meta information here, like https://raw.githubusercontent.com/AdobeDocs/pdfservices-api-documentation/develop/src/pages/overview/pdf-services-api/index.md 

refer first line

2022-09-02 07:52 UTC, piyuverma commented on src/pages/overview/pdf-electronic-seal-api/quickstarts.md
> +1. Download the digitally signed pdf.
Download the digitally signed pdf using download URI from above step.

2022-09-02 12:36 UTC, adityaganotra requested changes

2022-09-02 12:36 UTC, adityaganotra commented on src/pages/overview/pdf-electronic-seal-api/index.md
> +title: Document Services APIs | PDF Services API
shouldn't it be title: Document Services APIs | PDF Electronic Seal API

2022-09-02 12:51 UTC, merged