Docgen Table tag with markers
AdobeDocs/pdfservices-api-documentation pull request #704
Opened 2023-09-14 05:47 UTC by Dheeraj3reddy

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-09-14 10:01 UTC, Abhinandan578 requested changes

2023-09-14 10:01 UTC, Abhinandan578 commented on src/pages/overview/document-generation-api/complextableconstructs.md
> +Create both tables with their respective table markers. In the above example, the **school** tag acts as the array
Also are we not documenting on how to refer outer context and even root context

2023-10-12 14:00 UTC, piyuverma requested changes

2023-10-12 14:00 UTC, piyuverma commented on src/pages/overview/document-generation-api/tablewithmarkers.md
> +In the table row that needs to be dynamically expanded, place the table start marker in the first cell and table
"codified" table-start and "codified" table-end are necessary to be placed in each row (except header row). 
"codified" table-start is always followed by t"codified" able-end in the row or column depending on the table orientation, vertically or horizontally respectively. 
"codified" table-start needs to be placed in the first non-static cell of each row or column depending on the table orientation, vertically or horizontally respectively. 
"codified" table-end needs to be placed in the last non-static cell of each row or column depending on the table orientation, vertically or horizontally respectively.

2023-10-12 14:00 UTC, piyuverma commented on src/pages/overview/document-generation-api/tablewithmarkers.md
> +In the table row that needs to be dynamically expanded, place the table start marker in the first cell and table
In the "codified" table-start marker, an array field is required, which will be used to create the rows/columns in the table depending on the table orientation, vertically or horizontally respectively.

2023-10-12 14:00 UTC, piyuverma commented on src/pages/overview/document-generation-api/tablewithmarkers.md
> +Table tags with markers can also be used inside another table.
Nested Tables or Table inside Table is **only** supported using the new Table Markers ("codified"......)

2023-10-12 14:00 UTC, piyuverma commented on src/pages/overview/document-generation-api/tablewithmarkers.md
> +Table tags with markers can also be used inside another table.
Nested Table should contain its own Table Markers as per the rules defined above -> provide the link of the Rules from above.

Array Field used with "codified" table-start in the **inner/child** table should be the nested Array field used with "codified" table-start in the **outer/parent** table.

2023-10-12 14:00 UTC, piyuverma commented on src/pages/resources/openapi.json
> +          "zh-TW",
See this change, what is it about ?

2023-10-18 11:19 UTC, closed without merging