Python SDK 3.0 Dev Docs Update
AdobeDocs/pdfservices-api-documentation pull request #847
Opened 2024-05-16 10:49 UTC by jasnoors

Python SDK 3.0 Dev Docs Update

## Description

Python SDK 3.0 Dev Docs Update

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-05-16 12:43 UTC, varkumaradobe requested changes

2024-05-16 12:43 UTC, varkumaradobe commented on src/pages/overview/document-generation-api/quickstarts/python/index.md
> +![alt](shot7.png)
Please update the screenshot, below screenshot show old python version confusing users

<img width="794" alt="image" src="https://github.com/AdobeDocs/pdfservices-api-documentation/assets/119481807/1342c473-76a0-405d-8f92-62779f337821">

2024-05-16 12:43 UTC, varkumaradobe commented on src/pages/overview/document-generation-api/quickstarts/python/index.md
> +![alt](shot7.png)
Applicable in all 4 locations of quickstarts

2024-05-16 12:43 UTC, varkumaradobe commented on src/pages/overview/pdf-extract-api/gettingstarted.md
> +1. Install [Python 3.10](https://www.python.org/downloads/) or higher.
Docs level changes will be required under other languages as well for correctness.
![Uploading image.png…]()

2024-05-16 12:46 UTC, varkumaradobe commented
@jasnoors please add screenshot of logs of a working example

<img width="1512" alt="image" src="https://github.com/AdobeDocs/pdfservices-api-documentation/assets/119481807/390b2272-4f7d-4067-b2d4-be6c7875c084">
<img width="1457" alt="image" src="https://github.com/AdobeDocs/pdfservices-api-documentation/assets/119481807/ea1ea0be-1265-44ff-a26f-43f136e60276">

2024-05-22 09:53 UTC, hitesh-kumar-mahour approved these changes

2024-05-22 10:18 UTC, merged